//
// Created by Walter Toriola on 6/3/23.
//

#ifndef PROG4_ERRORS_H
#define PROG4_ERRORS_H


#define OPENDISK_FAILED -2
#define WRITEBLK_FAILED -3
#define READBLK_FAILED -4
#define TFS_MKFS_FAILED -5
#define MOUNT_FAILED -6
#define UNMOUNT_FAILED -7
#define TFS_OPEN_FAILED -8
#define TFS_DELETE_FAILED -9
#define DOES_NOT_EXIST -10
#define NO_FREE_BLOCKS_LEFT -11
#define ALREADY_OPEN -12
#define NOT_ALREADY_OPEN -13
#define TFS_WRITE_FAILED -14
#define NOT_FOUND_ROOT_DIRECTORY -16
#define NO_INODE_FOUND -17
#define TFS_READ_BYTE_FAILED -18

#endif //PROG4_ERRORS_H
